# This file was generated by GoReleaser. DO NOT EDIT.
cask "urlscan-cli" do
  version "2026.08.18"

  on_macos do
    on_intel do
      sha256 "e51d0ba34fe0c6ed1181dd4f47b0e484248febaba6c4828393d9349a3e346ddd"
      url "https://github.com/urlscan/urlscan-cli/releases/download/v#{version}/urlscan-cli_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "394bcf2ffff3b35871be1224d346a61446de209f2e7d165cdb658e157dcd8ad8"
      url "https://github.com/urlscan/urlscan-cli/releases/download/v#{version}/urlscan-cli_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "24ab9a6a526f1b942b7de1240b30e4d698ab6c3f4420f40634948326851b12ca"
      url "https://github.com/urlscan/urlscan-cli/releases/download/v#{version}/urlscan-cli_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "ccefcc7cca54b593817a722b0559922085a7dabbca741db064ac9a601a21988a"
      url "https://github.com/urlscan/urlscan-cli/releases/download/v#{version}/urlscan-cli_Linux_arm64.tar.gz"
    end
  end

  name "urlscan-cli"
  desc ""
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "urlscan"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/urlscan"]
    end
  end

  # No zap stanza required

end
