# This file was generated by GoReleaser. DO NOT EDIT.
cask "urlscan-cli" do
  version "2026.07.07"

  on_macos do
    on_intel do
      sha256 "c71a8be7438ad78a894e6a46b740f53c8782d14a794bfb078b7128d20285e496"
      url "https://github.com/urlscan/urlscan-cli/releases/download/v#{version}/urlscan-cli_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "2123d37e79cd7deb2bce6d96e01a2e11295bcfb763da00611f3858d120d0afbf"
      url "https://github.com/urlscan/urlscan-cli/releases/download/v#{version}/urlscan-cli_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "3b56099615a6aea4fdd3558a6f99835b65390db7d6e26ac878fa8bd2013a4928"
      url "https://github.com/urlscan/urlscan-cli/releases/download/v#{version}/urlscan-cli_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "a34fc4b17f0fd60c54e44fc5bd5a6bf784873521407b9bf3dd987fabbbfa6de9"
      url "https://github.com/urlscan/urlscan-cli/releases/download/v#{version}/urlscan-cli_Linux_arm64.tar.gz"
    end
  end

  name "urlscan-cli"
  desc ""
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "urlscan"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/urlscan"]
    end
  end

  # No zap stanza required

end
