# This file was generated by GoReleaser. DO NOT EDIT.
cask "urlscan-cli" do
  version "2026.09.17"

  on_macos do
    on_intel do
      sha256 "7f558ebf18c02f13068a1ae8888f7d23b2181863b90fab679ff57079dfc32866"
      url "https://github.com/urlscan/urlscan-cli/releases/download/v#{version}/urlscan-cli_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "666523b40adcc0692f67eb6bf9635b929f8c330133b71c67190b2280a4f7fae6"
      url "https://github.com/urlscan/urlscan-cli/releases/download/v#{version}/urlscan-cli_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "fbc532d163aecc3a139463f0cf336350a4bdac8bdac659ccd613359a40d5562c"
      url "https://github.com/urlscan/urlscan-cli/releases/download/v#{version}/urlscan-cli_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "f36ea0e67e6310f4a1fd9b116eac80749f78ca0ae590e151bf7ac911a1d6891f"
      url "https://github.com/urlscan/urlscan-cli/releases/download/v#{version}/urlscan-cli_Linux_arm64.tar.gz"
    end
  end

  name "urlscan-cli"
  desc ""
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "urlscan"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/urlscan"]
    end
  end

  # No zap stanza required

end
